name: urban bakery
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7792506418190897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#352b33'
    - '#877062'
    - '#a89186'
    - '#ebebdf'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
