name: urban bakery
favicon: null
layout_spectrum: 0.57852
typography_spectrum: 0.7792506418190897
title: Rustic bakery in Low Fell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#604933'
    - '#a8aa9d'
    - '#8d8573'
    - '#020403'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
