name: urban bakery
favicon: null
layout_spectrum: 0.3993739327415824
typography_spectrum: 0.7792506418190897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.732062382157892
  lightness: 0.17799608316272497
  saturation: 0.42916695424355567
  rhythmicContrast: 0.6855411794967949
purpose: []
